# Google Cloud Build configuration for deploying the bot
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/discord-tshirt-bot:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/discord-tshirt-bot:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-tshirt-bot:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-tshirt-bot:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'discord-tshirt-bot'
      - '--image=gcr.io/$PROJECT_ID/discord-tshirt-bot:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DISCORD_BOT_TOKEN=$$DISCORD_BOT_TOKEN,GOOGLE_API_KEY=$$GOOGLE_API_KEY,PRINTFUL_API_KEY=$$PRINTFUL_API_KEY,PRINTFUL_STORE_ID=$$PRINTFUL_STORE_ID'
    secretEnv: ['DISCORD_BOT_TOKEN', 'GOOGLE_API_KEY', 'PRINTFUL_API_KEY', 'PRINTFUL_STORE_ID']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/discord-bot-token/versions/latest
      env: 'DISCORD_BOT_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/google-api-key/versions/latest
      env: 'GOOGLE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/printful-api-key/versions/latest
      env: 'PRINTFUL_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/printful-store-id/versions/latest
      env: 'PRINTFUL_STORE_ID'

images:
  - 'gcr.io/$PROJECT_ID/discord-tshirt-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/discord-tshirt-bot:latest'
